execfile('../../../thesis_plot_defaults.py')
rc('lines', linewidth = 4)

lc_iip = loadtxt('lc-IIP.txt')
lc_iil = loadtxt('lc-IIL.txt')
lc_iib = loadtxt('lc-IIb.txt')
lc_iin = loadtxt('lc-IIn.average.txt')
clf()
plot(lc_iip[:,0]-15, lc_iip[:,1], ls='-', label='Type IIP')
plot(lc_iil[:,0]-10, lc_iil[:,1], ls='--', label='Type IIL')
plot(lc_iib[:,0]-21, lc_iib[:,1], lw=2, ls=':', label='Type IIb', dash_capstyle='round')
plot(lc_iin[:,0]-12, lc_iin[:,1], lw=2, ls='-.', label='Type IIn', dash_capstyle='round')
legend()
xlim(-20,150)
ylim(-0.5, 3)
gca().invert_yaxis()
xlabel(r'$t$ \,[days]')
ylabel(r'$R - R_{\textrm{max}}$ \,[mag]')
savefig('../plot_li11_lc_type2.pdf')